import React from 'react'

const Thirtyservice = () => {
    return (
        <header data-framer-name="Content Section" name="Content Section" class="box-border [-webkit-font-smoothing:inherit] place-content-center items-center flex flex-[0_0_auto] [flex-flow:column] gap-0 h-min overflow-hidden t767:pt-[30px] t767:px-5 t767:pb-[25px] b791:pt-10 b791:px-[30px] b791:pb-[35px] b9214:pt-[50px] b9214:px-[30px] b9214:pb-[45px] pt-[50px] px-[30px] pb-[60px] relative w-full">
            <div data-framer-name="Container" name="Container" class="box-border [-webkit-font-smoothing:inherit] place-content-center items-center t767:gap-10 t767:max-w-[390px] flex b791:gap-[50px] b791:max-w-[768px] flex-[0_0_auto] [flex-flow:column] b9214:gap-[60px] gap-[116px] h-min max-w-[98%] overflow-hidden p-0 relative w-full">
                <div data-framer-name="Content top" name="Content top" class="box-border [-webkit-font-smoothing:inherit] items-center b791:justify-center flex flex-[0_0_auto] [flex-flow:row] gap-[10px] h-min overflow-visible p-0 relative w-full">
                    <div data-framer-name="Image" name="Image" class="box-border [-webkit-font-smoothing:inherit] b9214:[aspect-ratio:1.3522_/_1] t767:flex-[1_0_0px] t767:h-auto t767:w-[1px] [aspect-ratio:1.4368932038834952/1] b791:w-[80%] flex-[0_0_auto] h-auto relative [transform:perspective(1200px)] b9214:w-[47%] w-[50%] z-[2] opacity-100">
                        <div data-framer-background-image-wrapper="true" class="box-border [-webkit-font-smoothing:inherit] absolute [border-radius:inherit] top-[0] right-[0] bottom-[0] left-[0]">
                            <img decoding="async" sizes="calc(min(100vw - 60px, 768px) * 0.8)" srcset="https://framerusercontent.com/images/vg9Pq1D9G8zQjX7mk0sGnwxTolg.png?scale-down-to=512 512w, https://framerusercontent.com/images/vg9Pq1D9G8zQjX7mk0sGnwxTolg.png?scale-down-to=1024 1024w, https://framerusercontent.com/images/vg9Pq1D9G8zQjX7mk0sGnwxTolg.png 1481w" src="https://framerusercontent.com/images/vg9Pq1D9G8zQjX7mk0sGnwxTolg.png" alt="" loading="lazy" class="box-border [-webkit-font-smoothing:inherit] b791:block hidden w-full h-full [border-radius:inherit] object-center object-cover"></img>
                            <img decoding="async" sizes="calc(min(100vw - 60px, (100vw - 60px) * 0.98) * 0.47)" srcset="https://framerusercontent.com/images/vg9Pq1D9G8zQjX7mk0sGnwxTolg.png?scale-down-to=512 512w, https://framerusercontent.com/images/vg9Pq1D9G8zQjX7mk0sGnwxTolg.png?scale-down-to=1024 1024w, https://framerusercontent.com/images/vg9Pq1D9G8zQjX7mk0sGnwxTolg.png 1481w" src="https://framerusercontent.com/images/vg9Pq1D9G8zQjX7mk0sGnwxTolg.png" alt="" loading="lazy" class="box-border [-webkit-font-smoothing:inherit] b9214:block hidden w-full h-full [border-radius:inherit] object-center object-cover"></img>
                            <img decoding="async" sizes="calc(min(100vw - 60px, (100vw - 60px) * 0.98) / 2)" srcset="https://framerusercontent.com/images/vg9Pq1D9G8zQjX7mk0sGnwxTolg.png?scale-down-to=512 512w, https://framerusercontent.com/images/vg9Pq1D9G8zQjX7mk0sGnwxTolg.png?scale-down-to=1024 1024w, https://framerusercontent.com/images/vg9Pq1D9G8zQjX7mk0sGnwxTolg.png 1481w" src="https://framerusercontent.com/images/vg9Pq1D9G8zQjX7mk0sGnwxTolg.png" alt="" loading="lazy" class="box-border [-webkit-font-smoothing:inherit] b791:hidden b9214:hidden block w-full h-full  [border-radius:inherit] object-center object-cover"></img>
                        </div>
                    </div>
                    <div data-framer-name="Patten" name="Patten" class="box-border [-webkit-font-smoothing:inherit] flex-[0_0_auto] b9214:h-[245px] h-[350px] b791:hidden b9214:left-[183px] left-[620px] absolute b9214:top-[36px] top-[55px] z-[1] [transform:perspective(1200px)] b9214:w-3/5 w-[45%] opacity-100">
                        <div data-framer-background-image-wrapper="true" class="box-border [-webkit-font-smoothing:inherit] absolute [border-radius:inherit] top-[0] right-[0] bottom-[0] left-[0]">
                            <img decoding="async" sizes="calc(min(100vw - 60px, (100vw - 60px) * 0.98) * 0.5996)" srcset="https://framerusercontent.com/images/lVcAP6mQeVH0wxnYZ0QdVBLSmdk.png?scale-down-to=512 512w, https://framerusercontent.com/images/lVcAP6mQeVH0wxnYZ0QdVBLSmdk.png 802w" src="https://framerusercontent.com/images/lVcAP6mQeVH0wxnYZ0QdVBLSmdk.png" alt="" loading="lazy" class="box-border [-webkit-font-smoothing:inherit] b9214:block hidden w-full h-full [border-radius:inherit] object-center object-cover"></img>
                            <img decoding="async" sizes="calc(min(100vw - 60px, (100vw - 60px) * 0.98) * 0.4497)" srcset="https://framerusercontent.com/images/lVcAP6mQeVH0wxnYZ0QdVBLSmdk.png?scale-down-to=512 512w, https://framerusercontent.com/images/lVcAP6mQeVH0wxnYZ0QdVBLSmdk.png 802w" src="https://framerusercontent.com/images/lVcAP6mQeVH0wxnYZ0QdVBLSmdk.png" alt="" loading="lazy" class="box-border [-webkit-font-smoothing:inherit] b9214:hidden block w-full h-full [border-radius:inherit] object-center object-cover"></img>
                        </div>
                    </div>
                </div>
                <div data-framer-name="Content bottom" name="Content bottom" class="box-border [-webkit-font-smoothing:inherit] t767:flex-col t767:gap-[30px] t767:justify-center items-center b791:flex-col b791:gap-10 b791:justify-center b791:w-[80%] flex flex-[0_0_auto] [flex-flow:row] h-min overflow-visible p-0 relative w-full">
                    <div data-framer-name="Title" name="Title" class="box-border [-webkit-font-smoothing:inherit] items-start justify-center flex t767:max-w-[unset] t767:w-full flex-[0_0_auto] b791:max-w-[unset] b791:w-full [flex-flow:column] gap-[22px] h-min b9214:max-w-[480px] max-w-[630px] overflow-hidden p-0 relative b9214:w-[52%] w-[45%]">
                        <div data-framer-component-type="RichTextContainer" class="box-border [-webkit-font-smoothing:inherit]  flex-[0_0_auto] h-auto [transform:perspective(1200px)] whitespace-pre-wrap w-full break-words outline-[none] flex flex-col justify-start flex-shrink-0 opacity-100">
                            <h2 data-styles-preset="nJtNjSFCn" class="text-primary font-semibold t767:text-[36px] b791:text-[45px] text-[56px] leading-[1.3em] tracking-[-1px] text-start">30+ YEARS OF SERVICE IN THE INDUSTRY.</h2>
                        </div>
                        <div data-framer-component-type="RichTextContainer" class="box-border [-webkit-font-smoothing:inherit]  flex-[0_0_auto] h-auto opacity-0 [transform:perspective(1200px)_translateX(0px)_translateY(80px)_scale(1)_rotate(0deg)_rotateX(0deg)_rotateY(0deg)_skewX(0deg)_skewY(0deg)_translateZ(0)] whitespace-pre-wrap w-full break-words outline-[none] flex flex-col justify-start flex-shrink-0">
                            <p data-styles-preset="LQ9CBsl_T" class="text-primary text-[18px] font-normal leading-[1.7em] tracking-normal ">We understand that taking the leap into solar can feel overwhelming, which is why education is core to our mission. Our solar consultants take the time to fully explain the technology</p>
                        </div>
                    </div>
                    <div data-framer-name="Image" name="Image" class="box-border [-webkit-font-smoothing:inherit] b9214:aspect-ratio:0.666667_/_1] b791:aspect-[usset] b791:bottom-[unset] b791:h-[550px] b791:relative b791:right-[unset] t767:aspect-[.875/1] t767:bottom-[unset] t767:h-auto t767:relative t767:right-[unset] t767:w-full b791:w-full [aspect-ratio:.7333333333333333/1] bottom-0 flex-[0_0_auto] h-auto absolute right-0 [transform:perspective(1200px)] b9214:w-[400px] w-[550px] z-[1] opacity-100">
                        <div data-framer-background-image-wrapper="true" class="box-border [-webkit-font-smoothing:inherit] absolute [border-radius:inherit] top-[0] right-[0] bottom-[0] left-[0]">
                            <img decoding="async" sizes="400px" srcset="https://framerusercontent.com/images/CPzVJhTb8sk9rsHXgBeyJ2Jrg.png?scale-down-to=1024 836w, https://framerusercontent.com/images/CPzVJhTb8sk9rsHXgBeyJ2Jrg.png 1232w" src="https://framerusercontent.com/images/CPzVJhTb8sk9rsHXgBeyJ2Jrg.png" alt="" loading="lazy" class="box-border [-webkit-font-smoothing:inherit] b9214:block hidden w-full h-full [border-radius:inherit] object-center object-cover"></img>
                            <img decoding="async" sizes="550px" srcset="https://framerusercontent.com/images/CPzVJhTb8sk9rsHXgBeyJ2Jrg.png?scale-down-to=1024 836w, https://framerusercontent.com/images/CPzVJhTb8sk9rsHXgBeyJ2Jrg.png 1232w" src="https://framerusercontent.com/images/CPzVJhTb8sk9rsHXgBeyJ2Jrg.png" alt="" loading="lazy" class="box-border [-webkit-font-smoothing:inherit] block b9214:hidden w-full h-full [border-radius:inherit] object-center object-cover"></img>
                        </div>
                    </div>
                </div>
            </div>
        </header>
    )
}

export default Thirtyservice
