import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
const unsansvar = localFont({
  src: "./fonts/UnSans-Variable.ttf",
  variable: "--font-unsans",
  // weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${unsansvar.variable}  antialiased`}
      >
        <div className="min-h-screen w-auto flex flex-col font-unsans content-center justify-start items-center bg-white h-min overflow-hidden relative">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
